### ISSUE TITLE
v0.6.7 fails

### ISSUE THREAD

**Issue by mxriverlynn** [anviljs/anvil.js#10]
I updated from whatever previous version i had, to v0.6.7 to see if that would fix my problem with the wrap and finalize, but now i can't run it at all:

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Cannot call method 'sort' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/anvil.js/node_modules/docco/lib/docco.js:141:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/anvil.js/node_modules/docco/lib/docco.js:155:4)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/anvil.js/lib/anvil.js:484:10)
    at Module._compile (module.js:441:26)
```

I get that error when I try to run `anvil` against my project

**Comment by arobson** [comment]
I saw that error locally after merging in the docco stuff but it went away after I changed the way the dependency had been specified in package.json and ran npm update. Looks like that was a coincidence and didn't actually fix the issue. I will try to repro and resolve shortly. Any chance running npm install docco -g gets anvil running again?

**Comment by mxriverlynn** [comment]
tried that, but it didn't help

**Comment by mxriverlynn** [comment]
is there a way to tell it to not run the docco task?

**Comment by aaronmccall** [comment]
@derickbailey just eliminate the "gendocs" key from build.json to prevent calls to docco.

**Comment by mxriverlynn** [comment]
I never had a gendocs key in mine. 

it doesn't matter if it's in there or not. adding it and configuring it correctly fail. removing it still fails.

**Comment by aaronmccall** [comment]
found the issue: docco proper (as in the ordinary NPM package) is not able to be used inside of javascript. anvil's package.json needs to specify docco like so '"docco": "https://github.com/andtan/flocco/tarball/master"'

**Comment by mxriverlynn** [comment]
how do i fix my local install while i wait for that to be fixed in the npm package for anvil?

**Comment by aaronmccall** [comment]
is anvil installed globally? in that case, you'd need to modify the docco key in anvil's package.json in your global node_modules (mine are in /usr/local/lib/node_modules) and run `npm update .` in the anvil node_module dir.

**Comment by mxriverlynn** [comment]
still failing for me, even after i manually clean out the original docco and then run "npm install" or "npm update" from within the anvil folder. 

i'll just wait til the anvil package is fixed in the npm registry

**Comment by aaronmccall** [comment]
I have submitted a pull request that should fix it

**Comment by ganarajpr** [comment]
I am waiting for this fix as well. I was following derick's marionette and wanted to test it out ( will try without anvil until then! ). @derickbailey Would it be possible to create a scaffolding for your marionette using anvil? 

I need anvil as a build script. This is a great tool. Keep up the good work. Would help, but am still a noob in the js world.

**Comment by mxriverlynn** [comment]
@ganarajpr i don't think anvil would be a good fit for that. it doesn't do file generating or template expansion for that purpose. it's real purpose is to be an opinionated build tool for js libraries / apps. 

fwiw, you don't need anvil to use marionette, only to build it. there are download links at the top of the marionette readme to get what you need for using marionette. if you're running in to issues or need help, open up an issue on the marionette issues page so we don't hijack the anvil issue page here :)

**Comment by arobson** [comment]
@derickbailey I have pulled in @aaronmccall's patch and re-published to npm. Really sorry I wasn't able to get to this sooner today. @aaronmccall to the rescue : ) 

I believe you can re-install specific versions of packages with this:

```
npm install anvil.js@0.6.6 -g
```

Not exactly comforting and I am sorry you were down for a day : ( The new version of Anvil has unit tests so hopefully I will catch mistakes like this one going forward.

**Comment by mxriverlynn** [comment]
no worries, yo. you have a day job. :)

i updated to the new version and it works now. thanks!
