### ISSUE TITLE
ignore anything other than .js or .coffee files

### ISSUE THREAD

**Issue by mxriverlynn** [anviljs/anvil.js#16]
the old version would only try to build and minify .js files. The new version is trying to build / minify everything, including the .DS_Store files that OSX generates.

!!! Error minifying .DS_Store : 
     Unexpected character '' (line: 9, col: 1, pos: 300)

Error
I can't specify anything other than a folder in the source setting other than a folder, either. if i specify src/*.js it looks for a folder called *.js

All of this is in my Marionette project, where I'm trying to use Anvil to build it. https://github.com/derickbailey/backbone.marionette

I can work around this issue by moving all of my support files (headers / footers, license, etc) in to a different folder, and by manually deleting the .DS_Store file before building... but it would be nice to have Anvil ignore files other than .js or .coffee, for the build / minify process

**Comment by arobson** [comment]
Marionette seems to be building ok now, I even added junk to the src folder to make sure it didn't get included or break the build.

I also made a few changes to the build file to test some things out and I've left notes. If you're interested, I can always submit a pull request for you to review.

```
 Note: gzip is not currently in this version of anvil but the old feature never worked. 
 The gzip output wouldn't load in browsers ( for me anyway )
```

## Single Build File

I personally wouldn't like maintaining two builds. The steps to consolidate may feel clunky and I understand if you're not interested, but I thought I'd share them just in case:

I added a amd.js and browser.js to your source folder. Their contents look like this:

### amd.js

```
 define(['jquery', 'underscore', 'backbone'], function($, _, Backbone){
      // import "backbone.marionette.js"
 return Backbone.Marionette; });
```

### browser.js

```
 // import "backbone.marionette.js"
```

### build.json

Then I added a name section which takes the default output that would have occurred and maps it to a different destination. You still end up with the same output as before ( minus the gzip files )

```
 "name": {
      "amd.js": "amd/backbone.marionette.js",
      "amd.min.js": "amd/backbone.marionette.min.js",
      "browser.js": "backbone.marionette.js",
      "browser.min.js": "backbone.marionette.min.js"
 }
```

## Finalization

I also pulled the license header off the source file and put it in license.txt. *\* You need to have a line feed at the end of that file. **. 

Then I added the finalize block to the build.json file:

```
 "finalize": { "header-file": "license.txt" }
```

## Docs

You can add a docs section to the build json or you can just choose the generator with --docco or --ape when calling anvil. So far it seems like they both have odd style quirks.

Hope this helps, I appreciate you helping me identify issues. Let me know if there are other things that would help. Any value in adding jasmine support to Anvil?

**Comment by arobson** [comment]
Commit f4a9b79 should address this, I'll wait to make sure you're not seeing the problem anymore.

**Comment by mxriverlynn** [comment]
@arobson thanks for all the detail here. i'm just now getting to this and i'm going to put in the changes that you suggested for a single build file. that looks much easier than what i'm trying to do. :)
