### ISSUE TITLE
Document that to build Anvil, you need to install Pygmants

### ISSUE THREAD

**Issue by mikehostetler** [anviljs/anvil.js#19]
Anvil uses anvil to build itself, which requires getting Docco to work.

For Docco to work, you need to install the Python library Pygments: http://jashkenas.github.com/docco/

Pygments is here: http://pygments.org/

There wasn't a great place to put developer documentation yet, so wanted to get this recorded here.

**Comment by arobson** [comment]
Hey Mike,

This is a bug in the package.json file. Using the wrong version of docco causes this issue. There is a version that doesn't require the Python package and the package file should have reflected that. Let's touch base on this and make sure I'm correct, I don't want to require Python packages for Anvil to work.

Thanks for catching this.
