### ISSUE TITLE
Mocha in-browser (or jasmine)

### ISSUE THREAD

**Issue by barclayadam** [anviljs/anvil.js#22]
Is there any way for Mocha (or other in-browser spec runners such as Jasmine) to be able to be hosted in the browser via. anvil, as pavlov was in a version before the reboot?

Before the reboot a pavlov page was completely generated on the fly, is that something that is making a return in some form or another? Some of the parts seem to be there (e.g. the anvilHook.js file for automatically refreshing) but others such as being able to automatically include all dependencies, and spec files is not there (or at least, I cannot find it :))

Perhaps the hosting could be configured to serve up these files from some special routes, say /ext.all.js to include all dependencies, /spec.all.js to include all spec files combined? Or something smarter, more useful....

And, without wanting to make this issue too dense, is there anyway to stop anvil copying unneeded files into the ext folder (pavlov.js, qunit.[js|css]).

**Comment by arobson** [comment]
### HTML page generation

This feature got cut for the rewrite because there is not currently a reliable way for Anvil to know what order script includes should occur. Using directory order is pretty broken on pretty much anything with more than just a few cross-dependencies. 

### Unneeded files

I will see what I can do about this one. Putting a symbolic link in the project to link back to these items felt dirty, but perhaps I can map a route to them via express so that they don't have to physically exist anywhere.

Thanks for your feedback, I appreciate knowing what features people care about and what elements of the development story need to get addressed. I can't make any promises at the moment, but I do have some ideas for how to get the testing story improved.

I will look into adding browser support for mocha or getting Jasmine in the loop.

**Comment by barclayadam** [comment]
### Page Generation

Good point about the ordering of script includes. Just to throw some thoughts out there, not sure what you have in mind with regards to the testing story so feel free to completely ignore me ;)
- For the ext folder we allow a references.[txt/js/etc] file that includes the order of the files as they should be included (just a list of file names). This would mirror the style used in src, to have a top-level file with a number of imports. I have, admittedly, not thought about this too much outside of my own requirements (a CoffeeScript library to be built for the browser) but typically any integration files (e.g. spec runners, examples) are going to include all dependency files in an order, followed by the library being built.
- For specs I tend to find spec suites should have files that are completely independent and therefore do not require any special ordering, save for perhaps a global file (or many) that should always be included first which add for example jasmine helpers / matchers. This could either rely on a special folder (helpers) or just directory ordering (make files start with an underscore). Not sure how magic this should (or should not!) be though.
  - A final thought is that specs typically require a number of dependencies (e.g. jasmine, sinon, sinon-jasmine integration) that I may not want to include with the other dependencies in ext, I want to separate what are 'production' and what are 'development' dependencies.

### Unneeded files

Having an express route for the use of built-in files would definitely be an improvement, although why are these files being used at all? As I have not specified a testing framework I would not have expected pavlov/qunit files to be available anywhere. The risk I'm worried about in particular is a version mismatch, causing problems on unsuspecting developers. A set of built-in express routes seems a clean way of providing the support you are providing.

None of the above is a show-stopper as of course I could stop being lazy and manage it myself, but then where is the fun in that! Been looking for a decent JavaScript build system so glad to have found anvil. Thanks!

**Comment by arobson** [comment]
Thanks for the detailed feedback. This is a huge help. Understanding what others are looking for will definitely help improve how versatile Anvil is.

I am currently working on two lines of development. One is fixing bugs and issues and the other is creating a more plug-in centered design for Anvil that should make it possible to address a lot more use cases and make it extensible. In the mean-time, I'm going to mull over your thoughts on resolving inter-library dependencies. It would be nice if Anvil could generate stub HTML pages again.

A fix to remove the file copying to ext should be coming soon.

**Comment by arobson** [comment]
Going to close this out; starting in RC3 and forward, testem integration supports running custom test pages in the browser so that users can choose any approach they like. Scaffolds could be created to help users generate test pages.
