### ISSUE TITLE
The uglifier needs to be a little stricter about file extensions

### ISSUE THREAD

**Issue by mikesten** [anviljs/anvil.js#28]
jquery.jscrollpane.js becomes jquery.min.jscrollpane.js instead of jquery.jscrollpane.min.js

**Comment by arobson** [comment]
I wasn't able to reproduce this exact issue, but I did see some odd behavior thanks to your report of this issue. After fixing that problem, I was able to build a small test project with the file one.two.three.js which was successfully minified to one.two.three.min.js.

I have published a new version of anvil to npm 0.7.6 that should address this and the other combiner issues you found. Thanks for your contributions!
