### ISSUE TITLE
Replace statement can be obeyed when inline

### ISSUE THREAD

**Issue by mikesten** [anviljs/anvil.js#29]
I was trying to bundle jQuery with a couple of plugins and found that Anvil was mangling some jQuery internals. I've written a quick test case:
https://github.com/mikesten/anvil.js/commit/f89f0c6534e4903feab094f82f0af8b8befb1ac6

My Regexp foo is weak though so I couldn't manage a fix. Let me know if you want a pull request for the test.

**Comment by arobson** [comment]
@mikesten, thanks for tracking this down and writing the test cases. The test for this appears to pass. I'm not clear what was happening before, but if your test case represented the problem you were seeing, this issue should be resolved as well.

I am going to close the issue, but re-open it if you continue to see problems. Thanks again.
