### ISSUE TITLE
documentation generator support

### ISSUE THREAD

**Issue by aaronmccall** [anviljs/anvil.js#3]
Hi Alex!

I was wondering if you were interested in having documentation generation in anvil.js. I would love to contribute support for [ape](https://github.com/nathan-lafreniere/ape) and [docco](http://jashkenas.github.com/docco/).

**Comment by aaronmccall** [comment]
PS -- I am currently testing all 3 (docco, ape and anvil.js) for use in some of my projects and thought it would be pretty cool to have the doc generation built into anvil.js.

**Comment by arobson** [comment]
Hey Aaron,

That sounds like an awesome idea. Contribution would be fantastic and I would probably use the heck out of it for some of the other projects I've been working on. I kept meaning to look into docco and have been putting it off. Anvil's source is pretty messy so just let me know if you have any questions. If it looks too daunting to dive into, I may see about adding support.

Thanks!

**Comment by ifandelse** [comment]
+1 on this idea!  Would be a great addition....

**Comment by aaronmccall** [comment]
Alex:

How about I contribute some code comment docs as well? It'll help me
to understand the code and others to contribute in the future.

## Aaron

Brevity is the soul of wit (and mobile email!).

On Feb 27, 2012, at 10:23 AM, Alex Robson
reply@reply.github.com
wrote:

**Comment by arobson** [comment]
Aaron,

You're a brave soul. If you happen to want help spelunking the depths of anvil, I will do what I can there. Anvil is the first project like it that I'd ever written for Node (and first major use of coffeescript) so it's... uh... got character.

It's also possible you'll have recommendations for refactoring or better code organization in general. Any contribution is really appreciated. I'm not fond of the source, but I do like what it does.

Alex

**Comment by aaronmccall** [comment]
Alex,

Take a look at my `code_docs` branch, if you want a sneak peak of what I'm up to. I'd love your feedback.

**Comment by arobson** [comment]
Hi Aaron,

Sorry I didn't respond sooner. This is looking really good so far, I didn't get a chance to review all of it, but I really appreciate the effort you've put in so far.

Thanks!

**Comment by aaronmccall** [comment]
Alex,

I've finished (pending feedback from you) my attempt to document the code. Please review: [code_docs](https://github.com/aaronmccall/anvil.js/tree/code_docs).

Thanks and have a fantastic Tuesday!

**Comment by aaronmccall** [comment]
If you like what you see (or when the code docs pass muster), I'll `merge --squash` the branch back into master and send a pull request.
