### ISSUE TITLE
$` in JS files being taken as a regexp match

### ISSUE THREAD

**Issue by mikesten** [anviljs/anvil.js#30]
While attempting to import Backbone I found Anvil treating $` (in Backbone's comments) as a Regexp replacement directive. 

Here's a testcase:
https://github.com/mikesten/anvil.js/commit/344c0b2520eec49552761b8c190365b70a05c876

Like the last one, let me know if you want me to wrap up a diff or pull request.

**Comment by arobson** [comment]
@mikesten, thanks for tracking this down and writing the test cases. The test for this appears to pass. There's no way to prevent the replace method from interpreting the $ as it was, so I have to perform an intermediate replace to something cheesy, then switch it back after the intended replace is done. Not ideal, but it seems to address the problem.

I am going to close the issue, but re-open it if you continue to see problems. Thanks again.
