### ISSUE TITLE
need a changelog

### ISSUE THREAD

**Issue by mxriverlynn** [anviljs/anvil.js#32]
It would be very beneficial to have a changelog of the things that have changed between versions. I keep mine in the readme of my projects, but even if it's a separate file, it would help a lot with upgrading and getting used to the new features as new versions are released.

fwiw, i write my change logs the same way i write documentation: as change happens. if i don't write the change log and the documentation changes as soon as i done with a small change, i won't remember what i changed or why.

**Comment by arobson** [comment]
Great suggestion. I've started one and went back to previous pull requests to tried to reconstruct something and will keep it going for future development.
