### ISSUE TITLE
flocco no longer exists. can't install anvil

### ISSUE THREAD

**Issue by mxriverlynn** [anviljs/anvil.js#33]
there's a direct dependency on https://github.com/andtan/flocco/tarball/master

this user and this repository no longer exist, so i can't install anvil anymore

**Comment by arobson** [comment]
Thanks for the heads up. That's a bummer. I'll see what I can do for the short-run.

**Comment by mxriverlynn** [comment]
short term suggestion: disable docco documentation feature? :)

**Comment by arobson** [comment]
As much as I dislike removing a feature, I really dislike the idea of Anvil having a python dependency. Until I can work out an alternative, docco support has been disabled. Don't install Anvil version 0.7.7 from NPM unless you're not using docco.
