### ISSUE TITLE
0.7.7 Issues getting started

### ISSUE THREAD

**Issue by madcapnmckay** [anviljs/anvil.js#38]
Followed the docs, for a new project.
1. anvil --lib MyProject
2. to the default build.json added "name": "myproject.js"
3. Added two files to src folder test1.js and test2.js

``` javascript
var SomeClass = function () {
    this.name = "Foo";
};
```

And

``` javascript
var SomeClass2 = function () {
    this.name = "Bar";
};
```

Build

The file myproject.js contains.

``` javascript
var SomeClass2=function(){this.name="Bar"} = "Bar";
};
```

Obviously this is wrong. I've repeated this a couple times, same result. I would guess that it's maybe because I didn't specify import comments but I would expect the js to be valid and just in the wrong order.

**Comment by arobson** [comment]
Based on what I understand of this test, I'm surprised Anvil is doing anything other than outputting test1.js and test2.js in the lib folder.

Without import statements Anvil's not meant to combine files at all. Let me know if I've totally missed the mark here.

**Comment by madcapnmckay** [comment]
Ok, that's what I thought. It seems because I specified a single output name it attempted to combine them all.I figured maybe if no imports were specified it would go by directory order or something. 

I was having issues with the import statements. If i included a test2.js import in the test1.js I received.

TypeError: Cannot read property 'fullPath' of undefined

Any idea what that could be?

**Comment by arobson** [comment]
Does the content of test1.js look like:

```
var SomeClass = function () {
    this.name = "Foo";
};

// import( "test1.js" );
```

**Comment by madcapnmckay** [comment]
My test1.js looks like the above but with test2.js in the import statement. Interestingly, i'm on my home machine now and I am not receiving the fullPath error. The import comments are working. 

If I specify in the build.json to use uglify the output is.

``` javascript
var SomeClass=function(){this.name="Foo"},SomeClass2=function(){this.name="Bar"}n () {
    this.name = "Bar";
};
```

Not the extra body and "n" character at the end of the second class.

If i omit the uglify, the output is unminified but otherwise correct js.

Any ideas.

**Comment by madcapnmckay** [comment]
Sorry for spamming, thought I'd raise all my issues in the same thread. I've added a few mocha tests, all is running fine from anvil. However if i run in CI mode, the first iteration runs my tests, I then update the js files, the watchers correctly rerun the build but no tests are run. It doesn't matter whether I add the mocha section in build.json or add it as a param i.e.

anvil --mocha --ci

**Comment by arobson** [comment]
Hi Ian,

I am not able to repro the uglify error you're seeing. What OS are you on? I was able to reproduce the CI and Mocha issues you were running into and found out that Mocha added a new JS API that I was able to use to simplify Anvil's Mocha runner and resolve that bug.

**Comment by madcapnmckay** [comment]
I'm on Win 7 x64. I've been building fine all weekend without uglify and with real code. I'll try my test case again tonight. Great news about the mocha CI stuff.

Cheers

**Comment by arobson** [comment]
Hey @ madcapnmckay,

Still using anvil? Let me know if you're still having issues with the newer version and we'll get it fixed or close this issue out.
