### ISSUE TITLE
CI + CoffeeScript compilation failure throws unhandled exception

### ISSUE THREAD

**Issue by barclayadam** [anviljs/anvil.js#40]
I'm using the CI option to build a CoffeeScript project, in addition to the socket.io support for automated reloads of my test suite but anvil will throw an exception and stop running should there be a compilation error in a file:

```
Error: Parse error on line 670: Unexpected ',' !!!
Post-process source files
Finalizing source files

C:\Users\Adam\AppData\Roaming\npm\node_modules\anvil.js\lib\anvil.js:1150
      ext = file.ext();
             ^
TypeError: Object #<Object> has no method 'ext'
```

Taking a look through the code seems to be because the error returned to the onComplete callback in the `Compiler.compile` method is being ignored in the `Anvil.processType` method, so post-processing continues without an output file to work on (`file` at the point of failure is an Error, not a file).

For myself I've added a crude check to not post-process if an error exists (`if(compiled[0] instanceof Error) { return self.stepComplete(type); }`) but this obviously completely ignores multiple files. This at least allows CI to continue to work and compile.

Thanks

**Comment by arobson** [comment]
This bug dates back to a version of anvil before extensions, please check out the new anvil and let me know if you're still having problems. Thanks!
