### ISSUE TITLE
Issue installing 0.8.15 related to "npm link npm --local"

### ISSUE THREAD

**Issue by rniemeyer** [anviljs/anvil.js#45]
Hello-
I have a number of repositories that use an older version of Anvil and I am looking to upgrade their build files to be compatible with the 0.8+ version.

I am having some issues getting Anvil installed on both of my Macs.  I have the latest version of node, npm, and uninstalled anvil completely. 

I run into an issue with the install doing `npm link npm --local`.  Here is my output:

```
$ sudo npm install anvil.js -g
npm http GET https://registry.npmjs.org/anvil.js
npm http 304 https://registry.npmjs.org/anvil.js
npm http GET https://registry.npmjs.org/colors/0.6.0
npm http GET https://registry.npmjs.org/commander/1.0.0
npm http GET https://registry.npmjs.org/fs-watch-tree/0.2.2
npm http GET https://registry.npmjs.org/machina
npm http GET https://registry.npmjs.org/mkdirp/0.3.3
npm http GET https://registry.npmjs.org/postal
npm http GET https://registry.npmjs.org/should/0.6.3
npm http GET https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/colors/0.6.0
npm http 304 https://registry.npmjs.org/machina
npm http 304 https://registry.npmjs.org/mkdirp/0.3.3
npm http 304 https://registry.npmjs.org/commander/1.0.0
npm http 304 https://registry.npmjs.org/fs-watch-tree/0.2.2
npm http 304 https://registry.npmjs.org/postal
npm http 304 https://registry.npmjs.org/should/0.6.3
npm http 304 https://registry.npmjs.org/underscore
npm http GET https://github.com/cujojs/when/tarball/1.3.0
npm http 200 https://github.com/cujojs/when/tarball/1.3.0
/usr/local/bin/anvil -> /usr/local/lib/node_modules/anvil.js/bin/anvil

> anvil.js@0.8.15 install /usr/local/lib/node_modules/anvil.js
> npm link npm --local

npm WARN prefer global npm@1.1.65 should be installed with -g
npm ERR! Error: EPERM, chmod '/usr/local/lib/node_modules/anvil.js/node_modules/npm/bin/npm-cli.js'
npm ERR!  { [Error: EPERM, chmod '/usr/local/lib/node_modules/anvil.js/node_modules/npm/bin/npm-cli.js']
npm ERR!   errno: 50,
npm ERR!   code: 'EPERM',
npm ERR!   path: '/usr/local/lib/node_modules/anvil.js/node_modules/npm/bin/npm-cli.js' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 12.2.1
npm ERR! command "node" "/usr/local/bin/npm" "link" "npm" "--local"
npm ERR! cwd /usr/local/lib/node_modules/anvil.js
npm ERR! node -v v0.8.14
npm ERR! npm -v 1.1.65
npm ERR! path /usr/local/lib/node_modules/anvil.js/node_modules/npm/bin/npm-cli.js
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, chmod '/usr/local/lib/node_modules/anvil.js/node_modules/npm/bin/npm-cli.js'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/lib/node_modules/anvil.js/npm-debug.log
npm ERR! not ok code 0
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/anvil.js/node_modules/.bin'
npm ERR! error rolling back  anvil.js@0.8.15 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/anvil.js/node_modules/.bin']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/anvil.js/node_modules/.bin' }
npm ERR! anvil.js@0.8.15 install: `npm link npm --local`
npm ERR! `sh "-c" "npm link npm --local"` failed with 50
npm ERR! 
npm ERR! Failed at the anvil.js@0.8.15 install script.
npm ERR! This is most likely a problem with the anvil.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm link npm --local
npm ERR! You can get their info via:
npm ERR!     npm owner ls anvil.js
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.2.1
npm ERR! command "node" "/usr/local/bin/npm" "install" "anvil.js" "-g"
npm ERR! cwd /Users/ryan/Dropbox/Projects/lab/Knockout-DelegatedEvents
npm ERR! node -v v0.8.14
npm ERR! npm -v 1.1.65
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/ryan/Dropbox/Projects/lab/Knockout-DelegatedEvents/npm-debug.log
npm ERR! not ok code 0
```

Any ideas? If there is more information that I can provide, please let me know.  Thanks!

**Comment by jcreamer898** [comment]
Are you using nvm? If not, I highly suggest it. There's some permissions issues that occur sometimes that could be causing your issues.

**Comment by arobson** [comment]
Hi Ryan,

Sorry that the new install is giving you trouble. I have occasionally seen these kinds of issues related to path/permissions on other machines that have been resolved when the user installs node via nvm.

My guess is that the user running npm install does not have the rights to change permissions on anything under /usr/local/lib/node_modules and that part of the linking is attempting to make npm-cli.js executable. (this line: npm ERR! stack Error: EPERM, chmod '/usr/local/lib/node_modules/anvil.js/node_modules/npm/bin/npm-cli.js' is what I'm basing my assumption on).

You could try running chown with a recursive flag in order to change the ownership of your node_modules. For example, if you user name was ryan, you could try:

``` shell
sudo chown -R ryan /usr/local/lib/node_modules/
```

Let me know what I can do to help. If you can tell me how you put together your node install, (for instance via brew), I can try setting up a VM sometime and working through the problem myself.

Thanks,
Alex

**Comment by rniemeyer** [comment]
Thanks guys.  I'll give `nvm` a shot.  On my laptop, Node was installed directly from the install pkg provided on nodejs.org.  I believe it was via homebrew on my other machine.

**Comment by ifandelse** [comment]
@rniemeyer I would recommend removing any node/npm assets you have installed before pulling [nvm](https://github.com/creationix/nvm) down. (Preventative medicine!)

**Comment by ifandelse** [comment]
@rniemeyer Also - if you have questions about how the structure of build.json files has changed, let us know!  We have some decent examples of current ones as well (check out [here](https://github.com/ifandelse/postal.js/blob/master/build.json), [here](https://github.com/ifandelse/machina.js/blob/master/build.json) or [here](https://github.com/ifandelse/monologue.js/blob/master/build.json)).

**Comment by rniemeyer** [comment]
Thanks for the responses.  I have it installed properly now that I am using `nvm`.  

Thanks for the links Jim, that should be helpful.  I think that I understand what I need to do with my build files as well. Hopefully, it will go smoothly.

**Comment by eliperelman** [comment]
Just FYI, Alex's suggestion had fixed this same issue for me:

``` sh
sudo chown -R eli /usr/local/lib/node_modules/
```

**Comment by rniemeyer** [comment]
@eliperelman - Thanks for verifying!  I'll try that next time and hopefully the next person that finds this thread can as well.
