### ISSUE TITLE
0.9.1 failed to install on linux

### ISSUE THREAD

**Issue by rauhryan** [anviljs/anvil.js#53]
if I run `sudo install anvil.js -g`

I get the following error 

```
npm ERR! Error: EACCES, symlink '../npm/bin/npm-cli.js'
npm ERR!  { [Error: EACCES, symlink '../npm/bin/npm-cli.js'] errno: 3, code: 'EACCES', path: '../npm/bin/npm-cli.js' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.2.0-33-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "link" "npm" "--local"
npm ERR! cwd /usr/local/lib/node_modules/anvil.js
npm ERR! node -v v0.8.18
npm ERR! npm -v 1.2.2
npm ERR! path ../npm/bin/npm-cli.js
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, symlink '../npm/bin/npm-cli.js'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/lib/node_modules/anvil.js/npm-debug.log
npm ERR! not ok code 0
npm ERR! anvil.js@0.9.1 install: `npm link npm --local`
npm ERR! `sh "-c" "npm link npm --local"` failed with 3
npm ERR! 
npm ERR! Failed at the anvil.js@0.9.1 install script.
npm ERR! This is most likely a problem with the anvil.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm link npm --local
npm ERR! You can get their info via:
npm ERR!     npm owner ls anvil.js
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-33-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "anvil.js"
npm ERR! cwd /home/rauhryan
npm ERR! node -v v0.8.18
npm ERR! npm -v 1.2.2
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/rauhryan/npm-debug.log
npm ERR! not ok code 0

```

**Comment by arobson** [comment]
How did you install Node? If you haven't installed it with NVM, then NPM won't have permissions to install any global modules. I'm guessing that's the issue given the paths like "/usr/local/bin/npm". You can either chose to sudo install all your global modules (ew) or you can back out your current install, snag [nvm](http://github.com/creationix/nvm) and be back up and running in a few minutes (only without the grossness of using sudo for global module installs).

If however you did use nvm, I'll take a look. Our crew primarily uses anvil on Linux boxes and generally when this kind of install blocker comes up it's usually path permissions.

**Comment by rauhryan** [comment]
i didnt' use nvm 

I make installed from the tarball

I will try nvm

Thanks

**Comment by arobson** [comment]
@rauhryan - going to close this one out unless nvm hasn't fixed the issue.

**Comment by ghost** [comment]
I had the same problem with MacOSX. Installing with nvm fixed it.

BTW This link from the quick-start is 404
http://anviljs.com/public/troubleshooting
