### ISSUE TITLE
scaffolding doesn't work?

### ISSUE THREAD

**Issue by szkrd** [anviljs/anvil.js#54]
The wiki says (in the quickstart) that a new project may be scffolded from scratch - is this true? To me, nothing happens (node 0.8.18, anvil 0.9.1, Win7 x64):

```
c:\szabi\dev\www\sandbox\anvil>anvil new demoProject
c:\szabi\dev\www\sandbox\anvil>ls -la
total 0
drwxrwxrwx   1 user     group           0 Feb  1 21:57 .
drwxrwxrwx   1 user     group           0 Feb  1 21:57 ..
```

Also note that `anvil install anvil.demo.scaffolds` gives me a npm 404 error.

If this shouldn't work, could you please remove the quickstart wiki page otherwise an error message would be nice; thank you!

**Comment by arobson** [comment]
@rosamez - sorry about that, would you try running the install command again and see if it installs correctly now without the 404?

**Comment by szkrd** [comment]
The demo scaffolds are fetched correctly now and the new demo scaffold works fine, thank you!
