### ISSUE TITLE
Anviljs website

### ISSUE THREAD

**Issue by szkrd** [anviljs/anvil.js#60]
Google's first result for anvilj is this page:
http://appendto.github.com/anvil.js/

Where the github link is broken - what is this site? Maybe it's just me, but it's pretty confusing. Also note that on anviljs.com (the _real_ site?) the navigation's scrollbar doesn't work and half of that menu is missing in 1366x768.

**Comment by mikehostetler** [comment]
Removed the github site at the first link, it should now 404 and Google should pick that up and adjust accordingly shortly.

The site is being worked on over the next few days and will be fully responsive soon.

**Comment by szkrd** [comment]
Thanks, hopefully google will throw away it from the index soon.
