### ISSUE TITLE
*-file settings don't work with .txt files?

### ISSUE THREAD

**Issue by mxriverlynn** [anviljs/anvil.js#9]
I'm trying to move all my "wrap" and "finalize" settings to external txt files, so that I don't have to maintain the info in the .json file.  it's loading my files correctly, but it's not appending any of the information to the header or footer, in the output. 

is this because i'm using .txt files? or ?

**Comment by mxriverlynn** [comment]
... ok, this is really odd now... of all the things that didn't work, it put the "finalize" / "header-file" (my license info) in to the gzipped files, but nothing else.

**Comment by mxriverlynn** [comment]
so, after getting the latest version of Anvil working, this still doesn't work. None of the output files contain any of my "wrap" or "finalize" stuff when using "header-file" and "footer-file" for finalize, or "prefix-file" and "suffix-file" for "wrap".

If i set the files to something that doesn't exist, i get the expected error saying it can't find the file. So that makes me think it is loading the files correctly, but not appending them to the output.

**Comment by arobson** [comment]
@derickbailey,

The new version of anvil should correctly handle this issue. I actually played around a bit with it and it was looking like this works. Would you be brave enough to install the new anvil version and give it a shot? Really trying not to throw junk over the wall. If you have a public repo you've been testing this in, let me know and I'd be happy to test the waters for you.

Thanks again,
Alex

**Comment by mxriverlynn** [comment]
looks like the new version is even more broken :(

the old version would only try to build and minify .js files. The new version is trying to build / minify everything, including the .DS_Store files that OSX generates.

```
!!! Error minifying .DS_Store : 
     Unexpected character '' (line: 9, col: 1, pos: 300)

Error
```

I can't specify anything other than a folder in the `source` setting other than a folder, either. if i specify `src/*.js` it looks for a folder called *.js

All of this is in my Marionette project, where I'm trying to use Anvil to build it. https://github.com/derickbailey/backbone.marionette

**Comment by mxriverlynn** [comment]
FYI - I can work around that issue by removing the .DS_Store file... but it would be nice to be able to limit what files it tries to compile and minify

**Comment by arobson** [comment]
Marionette seems to be building ok now, I even added junk to the src folder to make sure it didn't get included or break the build.

I also made a few changes to the build file to test some things out and I've left notes. If you're interested, I can always submit a pull request for you to review.

```
 Note: gzip is not currently in this version of anvil but the old feature never worked. 
 The gzip output wouldn't load in browsers ( for me anyway )
```

## Single Build File

I personally wouldn't like maintaining two builds. The steps to consolidate may feel clunky and I understand if you're not interested, but I thought I'd share them just in case:

I added a amd.js and browser.js to your source folder. Their contents look like this:

### amd.js

```
 define(['jquery', 'underscore', 'backbone'], function($, _, Backbone){
      // import "backbone.marionette.js"
 return Backbone.Marionette; });
```

### browser.js

```
 // import "backbone.marionette.js"
```

### build.json

Then I added a name section which takes the default output that would have occurred and maps it to a different destination. You still end up with the same output as before ( minus the gzip files )

```
 "name": {
      "amd.js": "amd/backbone.marionette.js",
      "amd.min.js": "amd/backbone.marionette.min.js",
      "browser.js": "backbone.marionette.js",
      "browser.min.js": "backbone.marionette.min.js"
 }
```

## Finalization

I also pulled the license header off the source file and put it in license.txt. *\* You need to have a line feed at the end of that file. **. 

Then I added the finalize block to the build.json file:

```
 "finalize": { "header-file": "license.txt" }
```

## Docs

You can add a docs section to the build json or you can just choose the generator with --docco or --ape when calling anvil. So far it seems like they both have odd style quirks.

Hope this helps, I appreciate you helping me identify issues. Let me know if there are other things that would help. Any value in adding jasmine support to Anvil?
